## DB H2
spring:
  datasource:
    url: jdbc:h2:mem:ecommerce
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    #defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:db_schema.sql

server:
  port : 8081

